import puppeteer from "puppeteer-core";
import http from "node:http";
import path from "node:path";
import {readFile,writeFile} from "node:fs/promises";
import {root,env} from "./director-tools.mjs";
const output=path.join(root,"out/director-r3"),mime={".html":"text/html; charset=utf-8",".css":"text/css",".js":"text/javascript",".png":"image/png",".webp":"image/webp",".svg":"image/svg+xml",".jpg":"image/jpeg",".ttc":"font/collection",".ttf":"font/ttf",".otf":"font/otf",".wav":"audio/wav"};
const server=http.createServer(async(req,res)=>{try{const target=path.resolve(output,decodeURIComponent(new URL(req.url,"http://localhost").pathname).slice(1));if(!target.startsWith(output+path.sep))throw Error("outside");const data=await readFile(target);res.writeHead(200,{"Content-Type":mime[path.extname(target)]||"application/octet-stream"});res.end(data);}catch{res.writeHead(404);res.end();}});
await new Promise(r=>server.listen(0,"127.0.0.1",r));const browser=await puppeteer.launch({executablePath:env.HYPERFRAMES_BROWSER_PATH,headless:true,args:["--no-sandbox","--use-angle=swiftshader","--disable-gpu"]});const page=await browser.newPage();await page.setViewport({width:1080,height:1920});const findings=[];const fonts=[];
const inspect=async frame=>page.evaluate(f=>{
 const tl=window.__timelines["director-r3"];tl.seek(f/60,false);
 const opacity=e=>Number(getComputedStyle(e).opacity),visible=e=>{while(e&&e.id!=="root"){if(opacity(e)<.05)return false;e=e.parentElement;}return true;};
 const rect=e=>{const r=e.getBoundingClientRect();return{x:r.x,y:r.y,right:r.right,bottom:r.bottom};};
 const texts=[...document.querySelectorAll(".main-copy,#slogan,#brand,#badge,#qr,#search,.provider,#illustrative")].filter(visible).map(e=>({id:e.id,bounds:rect(e),scroll:e.scrollWidth>e.clientWidth,lines:e.classList.contains("display-text")?e.getBoundingClientRect().height/parseFloat(getComputedStyle(e).lineHeight):0}));
 const sig=JSON.stringify([...document.querySelectorAll(".subject,#camera,.main-copy,#chat,#provider,#stream,#summary,#reply,#report,#saved,#cleanup-space,.display-text,#ending,#slogan,#brand,#download,.index,.zip-paper")].map(e=>{const s=getComputedStyle(e);return{id:e.id,transform:s.transform,opacity:s.opacity,filter:s.filter,height:s.height,top:s.top,color:s.color};}));
 return {frame:f,signature:sig,texts,saved:opacity(document.querySelector("#saved")),ending:opacity(document.querySelector("#ending")),end_components:["#slogan","#brand img","#brand span","#badge","#search","#qr"].map(q=>({selector:q,visible:visible(document.querySelector(q))})),slogan:opacity(document.querySelector("#slogan")),download:opacity(document.querySelector("#download")),report:opacity(document.querySelector("#report")),reply:rect(document.querySelector("#reply")),
 life:[...document.querySelectorAll("[data-life-id]")].map(e=>({id:e.id,crop:e.dataset.crop,opacity:opacity(e)})),lectures:[...document.querySelectorAll("[data-page]")].map(e=>({id:e.id,opacity:opacity(e)})),duration:tl.duration()};
},frame);
try{for(const locale of ["en","zh-Hans"]){const errors=[];const fn=e=>errors.push(String(e));page.on("pageerror",fn);await page.goto("http://127.0.0.1:"+server.address().port+"/"+locale+"/index.html",{waitUntil:"domcontentloaded"});await page.waitForFunction(()=>window.__directorReady);const ready=await page.evaluate(()=>window.__assetReadiness);
 const publicText=await page.evaluate(()=>document.querySelector("#root").innerText);
 if(/README\.md|lecture\.md|manifest\.json|Illustrative workflow|效果示意|Source pages|原始页图|LECTURE \/ 12/.test(publicText))throw Error("Public-facing engineering seam");
 const cdp=await page.createCDPSession();await cdp.send("DOM.enable");await cdp.send("CSS.enable");
 const fontCases=[[60,"#hook-0"],[246,"#selected"],[546,"#reading"],[990,"#report h2"],[1230,"#slogan p:first-child"],[1230,"#slogan p:last-child"]];
 for(const [frame,selector] of fontCases){await inspect(frame);const {root:doc}=await cdp.send("DOM.getDocument");const {nodeId}=await cdp.send("DOM.querySelector",{nodeId:doc.nodeId,selector});const proof=await cdp.send("CSS.getPlatformFontsForNode",{nodeId});const computed=await page.$eval(selector,e=>{const s=getComputedStyle(e);return{family:s.fontFamily,weight:s.fontWeight,variations:s.fontVariationSettings,synthesis:s.fontSynthesis,text:e.textContent};});const expected=locale==="en"?"Inter":"Source Han Sans";
 if(!proof.fonts.length||proof.fonts.some(f=>!f.isCustomFont||!f.familyName.includes(expected)))throw Error("Font fallback: "+locale+" "+selector+" "+JSON.stringify(proof));
 if(computed.weight!==(locale==="en"?"600":"700"))throw Error("Wrong display weight "+selector);
 fonts.push({locale,frame,selector,computed,platform:proof.fonts});}
 await cdp.detach();
 const frames=[0,21,60,130,180,246,299,360,420,450,504,546,582,629,660,696,738,786,822,870,918,990,1049,1050,1074,1080,1158,1229,1230,1231,1242,1248,1350,1500,1559];const samples=[];for(const f of frames)samples.push(await inspect(f));const baseline=new Map(samples.map(s=>[s.frame,s.signature])),shuffled=[1559,60,990,546,130,1500,0,738,299,1248,504,60,1559,546];const mismatches=[];const diffs=[];for(const f of shuffled){const got=(await inspect(f)).signature;if(got!==baseline.get(f)){mismatches.push(f);const a=JSON.parse(baseline.get(f)),b=JSON.parse(got);diffs.push({frame:f,diff:b.filter((e,i)=>JSON.stringify(e)!==JSON.stringify(a[i])).map(e=>({before:a.find(x=>x.id===e.id),after:e}))});}}await writeFile(path.join(output,"seek-diff-"+locale+".json"),JSON.stringify(diffs,null,2));
 const clipping=samples.flatMap(s=>s.texts.filter(t=>t.bounds.x<79.5||t.bounds.y<159.5||t.bounds.right>920.5||t.bounds.bottom>1550.5||t.scroll||t.lines>2.05).map(t=>({frame:s.frame,...t})));
 const saved=samples.find(s=>s.frame===1074);findings.push({locale,public_test_seams:"NONE",errors,ready,duration:samples[0].duration,seek_mismatches:mismatches,clipping,saved_before_departure:saved.saved===1&&saved.lectures.every(e=>e.opacity===1),middle_life_hidden:samples.filter(s=>s.frame>=450&&s.frame<=990).every(s=>s.life.every(p=>p.opacity===0)),report_hold:samples.filter(s=>s.frame>=918&&s.frame<=1049).every(s=>s.report===1),end_stable:samples.filter(s=>s.frame>=1230).every(s=>s.ending===1&&s.slogan===1&&s.download===1&&s.end_components.every(x=>x.visible)),samples});page.off("pageerror",fn);}}finally{await browser.close();server.close();}
await writeFile(path.join(root,"review/director-r3/FONT_PROOF.json"),JSON.stringify({method:"Actual CDP CSS.getPlatformFontsForNode, real web fonts, no font-synthesis",checks:fonts},null,2));
await writeFile(path.join(output,"dom-qa.json"),JSON.stringify(findings,null,2));console.log(JSON.stringify(findings.map(({samples,...x})=>x),null,2));if(findings.some(x=>x.errors.length||x.seek_mismatches.length||x.clipping.length||!x.saved_before_departure||!x.middle_life_hidden||!x.report_hold||!x.end_stable||x.duration!==26))process.exitCode=1;
